package app.sargis.khlopuzyan.alias.utils.constant

interface SharedPref {

    companion object {
        const val SHARED_PREF_APP_NOT_FIRST_TIME = "APP_FIRST_TIME"
        const val SHARED_PREF_NUMBER_OF_WORDS = "NUMBER_OF_WORDS"
        const val SHARED_PREF_ROUND_TIME = "ROUND_TIME"
        const val SHARED_PREF_DEFAULT_TEAM_COUNT = "DEFAULT_TEAM_COUNT"
        const val SHARED_PREF_IS_GAME_SOUND_ENABLED = "GAME_SOUND"
        const val SHARED_PREF_MISSED_WORD_PENALTY = "MISSED_WORD_PENALTY"
        const val SHARED_PREF_APP_LANGUAGE = "APP_LANGUAGE"
        const val SHARED_PREF_GAME_WORD_LANGUAGE = "GAME_WORD_LANGUAGE"
        const val SHARED_PREF_WORD_TRANSLATE_LANGUAGE = "WORD_TRANSLATE_LANGUAGE"
        const val SHARED_PREF_IS_WORD_TRANSLATE_ENABLED = "IS_WORD_TRANSLATE_ENABLED"
    }

}